package app.model;

import static lombok.AccessLevel.PROTECTED;

import java.util.ArrayList;
import java.util.List;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

/**
 * 09/06/2022.
 *
 * @author Laurent Lamiral
 */

@Data
public class MyGraph {

	private List<Vertex> vertices = new ArrayList<>();

	@Getter(PROTECTED)
	@Setter(PROTECTED)
	private int autoGeneratedId;

}
